### ISSUE TITLE
The config doesn't always seem to save changes

### ISSUE THREAD

**Issue by sbatson01** [VCCE/VCC#1]
Setting the Joystick preferences, they don't seem to stay after exit and restart of VCC

**Comment by BGPierce** [comment]
If you are running a Win7-Win10 system, you must set VCC to run as Administrator.
Right-click your VCC icon, select properties, click the Compatibility TAB, check "Run as Administrator"
Click "OKAY"
Now your config will be saved each time you exit VCC and it will retain your config settings.
This is a Win7-Win10 permissions issue. Newer windows versions don't like programs writing to "Program Files (x86)" or "Program Files" (98, XP & Vista didn't care), and hopefully will be resolved soon.
(it's in the VCC manual)

If this doesn't solve the problem, let us know and we'll investigate further.
Thanks,
B.P.

**Comment by sbatson01** [comment]
Even’t if my login account is in the Windows Administrators Group?

**Comment by sbatson01** [comment]
Strange, it’s working now. I didn’t change anything. Thanks.

FYI, I’m running it on Windows 7 Pro.

**Comment by BGPierce** [comment]
Yes, the change needs to be made even if you're administrator. Leave it to Microsoft for administrator to have to ask for administrator's privileges that only the administrator can approve...
 
 
 
-----Original Message-----
