### ISSUE TITLE
Paste is not following keyboard settings

### ISSUE THREAD

**Issue by ecm-bitflipper** [VCCE/VCC#102]
When pasting text, it appears that the paste functionality is not following the keyboard settings.  Even though I have the keyboard settings to correctly map [] (brackets), pasting those characters always ends up with 89.

I am using VCC 2.1.0.6-beta.

**Comment by ejaquay** [comment]
Correct.  Paste bypasses keyboard input and therefore keymapping.   It may
however be possible to modify the paste function to allow sending
brackets.  Will look into this when we get a chance.

**Comment by ecm-bitflipper** [comment]
I am attempting to test a little assembly language routine for a unit driven by a 6803 microprocessor.  Limiting myself to registers A,B,D,X and the operations supported by that microprocessor, the color computer environment is a good test bed.  I was able to edit the fouled lines manually in EDTASM++ and move on so I am not blocked by this "bug".  I just thought I would bring it to your attention.  Thanks though for your response.

**Comment by ejaquay** [comment]
The characters "()[]{}<>\|/-!@#$%^&*" all paste correctly as of version VCC2.1.9.1-pre2.  The latest pre-release can be found on github.  Note that the paste function most closely matches the "Natural" mapping.
