### ISSUE TITLE
Closes after Robotron finish de-compression

### ISSUE THREAD

**Issue by JAVITech** [VCCE/VCC#108]
Robotron v0.5 does not run. The loader finishes de-compression and VCC closes.
Windows 10 PC.

**Comment by klinems** [comment]
It runs on VCC 2.0.1d. 

 

Readme:

 

Almost complete version of ROBOTRON for the CoCo 3

 

This is a conversion of the original Arcade ROMs covered to work on CoCo 3 hardware.

 

I've gotten bored with this project and won't be working on it anymore.  It is

fully playable, but the audio needs work and the game has a few slow down

issues.

 

To play it use the DSK image and type RUN"ROBOTRON <ENTER>

Press 5 to insert Coin, 1 or 2 to start a one or two player game.

 

Joysticks are required

 

Glen Hewlett

 

 

From: JAVITech ***@***.***> 
Sent: 17 October 2022 19:16
To: VCCE/VCC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VCCE/VCC] Closes after Robotron finish de-compression (Issue #108)

 

Robotron v0.5 does not run. The loader finishes de-compression and VCC closes.

**Comment by ejaquay** [comment]
Seems to run on 2.1.9.0
