### ISSUE TITLE
Version 2.0.1f still shows "e"

### ISSUE THREAD

**Issue by Alpengreis** [VCCE/VCC#11]
Thank you for new version 2.0.1f.

Unfortunately it still shows version 2.0.1e - not a big deal but on the other side also not "nice".

Kind regards!

**Comment by BGPierce** [comment]
Yes, that was pointed out to me right after I released it. I have another release coming up and I will correct it then.

Thanks again,
Bill


-----Original Message-----

**Comment by Alpengreis** [comment]
No problem and thank you!

Then I would say, I close this case already ...
