### ISSUE TITLE
Pasting lowercase letters doesn't work

### ISSUE THREAD

**Issue by PsychoSavant** [VCCE/VCC#137]
I love this tool but I wanted to point out a shortcoming/bug that when you paste code into it if you have lowercase characters in your print statements they all get converted to uppercase. Makes making pretty formatted text difficult when there is a lot of prints.

**Comment by BGPierce** [comment]
We'll definitely look into that. Now that I think about it, seems like there was an issue with the way the Coco & PC code their lower case. It should be fixable though.
    On Monday, July 31, 2023 at 08:24:28 PM EDT, PsychoSavant ***@***.***> wrote:  
 
 


I love this tool but I wanted to point out a shortcoming/bug that when you paste code into it if you have lowercase characters in your print statements they all get converted to uppercase. Makes making pretty formatted text difficult when there is a lot of prints.

**Comment by jimrye** [comment]
The paste function works as if the user is typing the text manually. Pasting lowercase works if you press SHIFT-CAPS LOCK first, to put it in lowercase mode. Otherwise, yes, everything gets converted into uppercase.
