### ISSUE TITLE
Pressing F11 key opens full screen mode, but can't find in documentation.   

### ISSUE THREAD

**Issue by Ralph423** [VCCE/VCC#140]
I find it still useful if it is a forgotten function.  Only problem, I discovered that Windows Defender attacks Vcc.exe when i invoke the Fll key. I have restored Vcc, and added Vcc to Defender exclusions list.  Other wise Defender has no detection for Vcc.

**Comment by ejaquay** [comment]
Basic function keys including F11 are listed under Help About Vcc. 
We don't want to pay for a signing certificate so you might have to unblock Vcc.exe if check apps and files is on in Windows Security.

**Comment by BGPierce** [comment]
The "F11", full screen key is documented in the manual under... wait for it... "Function Keys", which is a list of all function key actions.
    On Monday, August 21, 2023 at 10:47:09 AM EDT, Ralph423 ***@***.***> wrote:  
 
 


I find it still useful if it is a forgotten function. Only problem, I discovered that Windows Defender attacks Vcc.exe when i invoke the Fll key. I have restored Vcc, and added Vcc to Defender exclusions list. Other wise Defender has no detection for Vcc.

**Comment by ejaquay** [comment]
For me when windows defender flags VCC it is that WIndows Security Real-time protection detects a usage pattern it does not like.  Has happened to me two or three times in the past few years.  Haven't nailed down what exactly triggers it.  It may be that VCC sometimes shuts down improperly (happens on occasion while testing buggy code changes).  I don't know for sure.  But when it has happened toggling Real-time protection in Windows Security Virus & threat protection seems to clear it.  After that running defender scans on vcc.exe shows no threats.
