### ISSUE TITLE
Hi-res Text Modes (WIDTH 40/80) Blinking Text Attribute Doesn't Work 

### ISSUE THREAD

**Issue by dragonbytes** [VCCE/VCC#146]
Using version 2.1.0.8. To reproduce, at the BASIC prompt, type WIDTH 40 or WIDTH 80 and ENTER. Then issue an ATTR 0,0,B and ENTER. On real hardware as well as other emulators, the OK prompt as well as subsequent keyboard input should be constantly blinking.

**Comment by ejaquay** [comment]
Fixed with pull request #161

**Comment by dragonbytes** [comment]
thank you!!! 😀
