### ISSUE TITLE
allow automatically typing commands on startup

### ISSUE THREAD

**Issue by trs-eric** [VCCE/VCC#148]
I would love a feature where VCC can enter some set of text for you after startup.

In MAME this is accomplished with the "autoboot" flag, the system will waiting for x number of seconds and then start sending keyboard input autonomously. See here: https://docs.mamedev.org/commandline/commandline-all.html#scripting-options

This could be part of the debugger options. This would make development using VCC much simpler so one does not have to load their program by hand every time they save out a new image and restart VCC.

**Comment by ejaquay** [comment]
Interesting idea.  In the past I have tried to get Vcc to automatically run "DOS" after it starts but I ran into timing issues that I did not have time to figure out.
