### ISSUE TITLE
Create option flags for command line console use that will override individual settings on startup

### ISSUE THREAD

**Issue by trs-eric** [VCCE/VCC#149]
I would like to have option flags available on the command line console that will override individual settings. For example:

c:> vcc -cpu=6309 

Would override the settings on vcc and start it up using the 6309 CPU. 

Specifically having the ability to manage the cartridge, floppy, and tape configuration would be essential.

This would allow VCC to be integrated with 3rd party tools and applications like development tools and game library managers such as Launchbox.

**Comment by ejaquay** [comment]
A better way is use the -i option to specify a different .ini file entirely:
   C> vcc -i ..\appdata\Roaming\vcc\n6809.ini
Any changes made using the menus will then be written to n6809.ini instead of the standard vcc.ini.   Use a different .ini file for each special situation you want.

**Comment by darkfalzx** [comment]
A more robust set of command line parameters could be highly useful for integration with front-ends, such as Launchbox, where one could fire up software with a single key-press, and without dealing with various configurations.
Could also use MAME/MESS-like feature of passing an auto-boot text string from command line - -autoboot_command "\nLOADM“POOYAN”:EXEC\n" or something like that.

**Comment by ejaquay** [comment]
Create a windows shortcut with command line containing the binary to autorun:   vcc-exe-path\vcc  [-i \<custom initfile>] <myprogram.bin> 
Then you can just click the shortcut.

**Comment by ejaquay** [comment]
Request #164 adds '-p' option to autopaste basic text when vcc starts.

Example; autostart nitros9 using nitros.ini for settings:

   C> vcc -i nitros.ini -p dos

Vcc options can be set in the ini file so being able to specify which ini to use should suffice for setting cpu type, speed, carts loaded, mounted disks, and many other things.   Ini files can be modified with notepad while Vcc is not running.
