### ISSUE TITLE
6309 TFM instruction bug 

### ISSUE THREAD

**Issue by jimrye** [VCCE/VCC#156]
From Michael Everson in the Facebook VCC User Group
Hi,
I am working on my own emulator for the 6309 and noticed that the code in VCC that handles TFM does not handle the incrementing and decrementing of the source and destination registers properly. I have tested this on a real 6309 and have discovered that the registers get updated as they are used and NOT at the completion of the memory transfer cycle. This means that if the source and target registers are the same (i.e. TFM X+,X+) the emulator will produce incorrect behavior. VCC does the read and the write before updating the registers. This is NOT how the real 6309 does it.
void Tfm1(void)
{ //1138 TFM R+,R+ 6309
if (W_REG == 0)
{
CycleCounter += 6;
PC_REG++;
return;
}
postbyte=MemRead8(PC_REG);
Source=postbyte>>4;
Dest=postbyte&15;
if (Source > 4 || Dest > 4)
{
InvalidInsHandler();
return;
}
temp8 = MemRead8(*xfreg16[Source]);
MemWrite8(temp8, *xfreg16[Dest]); <- if the registers are the same, data will be written to the wrong location
(*xfreg16[Dest])++;
(*xfreg16[Source])++;
W_REG--;
CycleCounter += 3;
PC_REG -= 2;
}
This what the output should look like:
Given the memory content is this before execution:
01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 10
Executing: TFM X+,X+ where X is pointing at the memory containing the pattern above should yield: (this is from a real 6309)
01 01 03 03 05 05 07 07 09 09 0B 0B 0D 0D 0F 0F
Michael Evenson

**Comment by jimrye** [comment]
It looks like this might be a fairly simple fix. Doing some testing first.

**Comment by ejaquay** [comment]
Fixed in version 2.1.8.2
