### ISSUE TITLE
Vcc crash on selecting quit from Virtual program

### ISSUE THREAD

**Issue by Ralph423** [VCCE/VCC#175]
I often get a crash from exiting TW128-HD. Not from TW128, or TW80.

Description
Faulting Application Path:	C:\Users\GP_2\Desktop\VCC\Vcc.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	Vcc.exe
Application Version:	2.1.8.2
Application Timestamp:	6567ab21
Fault Module Name:	Vcc.exe
Fault Module Version:	2.1.8.2
Fault Module Timestamp:	6567ab21
Exception Code:	c0000005
Exception Offset:	0006e363
OS Version:	10.0.19045.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	cf47
Additional Information 4:	cf47bb3890b24e55821fcecda3da7dd4

Extra information about the problem
Bucket ID:	2c9a1826a9f6f1f91ab61235b7ba9b15 (1924745912672492309)

**Comment by ejaquay** [comment]
How to reproduce.  What is TW128-HD?  

Exception address 0006e363 is probably in tccgraphics.c near line 6333
but there is no obvious instruction there that would cause an access violation. Unfortuanatly this is an not the current version of VCC so debugging information is not availiable.

**Comment by BGPierce** [comment]
TW128 HD is Telewriter 128 recoded for the Coco3. I think the HD is where they fixed the problem with Telewriter being hard coded for drives 0 & 1, allowing use of any drives, including hard drives. There should be a copy in the Coco Archives.
    On Sunday, February 11, 2024 at 08:57:10 PM EST, Ed Jaquay ***@***.***> wrote:  
 
 


How to reproduce. What is TW128-HD?

Exception address 0006e363 is probably in tccgraphics.c near line 6333
but there is no obvious instruction there that would cause an access violation. Unfortuanatly this is an not the current version of VCC so debugging information is not availiable.

**Comment by Ralph423** [comment]
The Crash happens on selecting quit from TW128-HD installed on Virtual Hard drive systems. Still get crash after updating to latest portable version of Vcc.

Source
Vcc

Summary
Stopped working

Date
‎2/‎11/‎2024 7:53 PM

Status
Report sent

Description
Faulting Application Path:	C:\Users\GP_2\Desktop\VCC\Vcc.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	Vcc.exe
Application Version:	2.1.8.3
Application Timestamp:	65b802fc
Fault Module Name:	Vcc.exe
Fault Module Version:	2.1.8.3
Fault Module Timestamp:	65b802fc
Exception Code:	c0000005
Exception Offset:	0006f323
OS Version:	10.0.19045.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	cf47
Additional Information 4:	cf47bb3890b24e55821fcecda3da7dd4

Extra information about the problem
Bucket ID:	a748bd60202a948cc85c9a8d3edc9273 (1755447886203359859)

**Comment by ejaquay** [comment]
Debugger associates the exception offset with line 6317 of tcc1014graphics.c  This code line is used to update the display and the exception is likely caused by a bad index to the hires surface array.  I can not get the error to occur on my PC but that does not mean it will not occur with other video hardware or os version. I can add code to force the calculated index to fit in the array and that should prevent the crash.

**Comment by Ralph423** [comment]
I found that no crash happens when using virtual floppy to load TW80-HD. I have only tested on RSDOS, and RGBDOS.
Probably not worth the effort to fix this minor, and rare issue.
