### ISSUE TITLE
Something I noticed about loading a differrent configuration with out restarting Vcc

### ISSUE THREAD

**Issue by Ralph423** [VCCE/VCC#177]
If I swap between RSDOS, RGBDOS, or Becker configuration , some of the settings seem to ghost into the newly loaded configuration.  For example, I have 4  floppy disk images mounted on RGBDOS, and they will automatically be mounted for my becker hdbdos. I can temporarily change what is mounted on the becker, but it will come back the next time I load becker config.

Also some otherwise empty MPI slots seem to ghost over from previously loaded config. Oddly enough, there seems to be no serious side effects.

Is it a no no to run multiple instances of Vcc?

**Comment by ejaquay** [comment]
Unless the command line -i option is used VCC starts using  %APPDATA%\VCC\VCC.ini for settings. After VCC starts you can use the File menu, Load Config item to change the ini file to anything you want.  Once that is done any configuration you do will be saved to that file.  I use the -i option in VCC shortcuts to automatically load different configurations. I can just click on the Icon I want to startup VCC with the config I want.

**Comment by Ralph423** [comment]
Got that working for me now. Thank you.
