### ISSUE TITLE
DSK image via command line in Fullscreen and vcc.ini questions

### ISSUE THREAD

**Issue by northstarex** [VCCE/VCC#178]
Hello

Is it possible to create a DSK image via command line that starts via run "space" and is displayed directly in the full screen?

Is it possible to change the VCC.INI location. For example, move it to the VCC directory?

Is there a solution?

Thx :)

**Comment by ejaquay** [comment]
I don't fully understand the first question but VCC can only create a new disk via the  Cartridge disk insert menu, which is not available when running full screen.

The answer to the second question is yes.

VCC.INI can be moved but VCC will look for it in %APPDATA%\VCC\VCC.ini  unless VCC is started with the command line option -i <ini file path>,  for example: C> vcc -i %USERPROFILE%\my.ini

**Comment by BGPierce** [comment]
As a warning, putting the VCC.ini in the VCC program folder under Win 7-11 will result in the ini file being "Read Only" and no new configurations can be saved unless VCC is run in "Administrator Mode". This is a Windows 7-11 issue and not a VCC issue. This is the very reason vcc.ini was moved to "%APPDATA%\VCC" per Windows instruction for such files. Any version of Windows before Win 7 does not apply it is possible to save the vcc.ini file in the VCC program folder.
    On Monday, February 12, 2024 at 08:12:04 PM EST, Ed Jaquay ***@***.***> wrote:  
 
 


I don't fully understand the first question but VCC can only create a new disk via the Cartridge disk insert menu, which is not available when running full screen.

The answer to the second question is yes.

VCC.INI can be moved but VCC will look for it in %APPDATA%\VCC\VCC.ini unless VCC is started with the command line option -i , for example: C> vcc -i %USERPROFILE%\my.ini
