### ISSUE TITLE
Multiple filepaths needed

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#29]
Currently, VCC maintains 1 single filepath. When you open a file dialog of any kind to mount a dsk, vhd, or rom, etc, VCC remembers that path, Then when you go to load/mount something different it comes up in the last path used.
As a habit, I have different folders on my PC for Dsk images, VHD images, and Rom images, etc. It would be nice if we could set 'default' folders for various filetypes. The needed ;default pathlists are:

CCC, ROM, DLL - Rom cart images. Loaded through the Cart port & MPI.
ROM - System roms. Loaded by the various DLLs and VCC itself. Also used in "FD502 Config" for external roms
DSK, VDK, DMK - Disk images. Used by fd502.dll
VHD - Virtual Hard Drive images. Used by harddisk.dll
IMG - SD card images. Used by SuperIDE.dll
Cas, WAV - Cassette image files. Used in "Config/Tape"
TXT - Printer text files. Created when using VCC's virtual printer in "Config/Bitbanger"

I think that about covers all the various file types VCC uses. Each should retain it's own filepath and be saved with the vcc.ini file.
B.P.

**Comment by BGPierce** [comment]
This has been resolved, but one problem, after closing the file diaolog, the VCC UI has lost focus and you must click the screen or window bar to regain focus.

**Comment by Wersley** [comment]
Which open file dialog?  The code has multiple instances of the same code for handling opening files.

**Comment by BGPierce** [comment]
All file dialogs in general. Once you close them, the main UI does not get the focus returned and you have to click somewhere in the VCC window for focus to come back. The focus DOES come back on the Config menu.
On further investigation, I find the "MPI" cart slots return to the same fold as the fd502. They need to be separate, as the MPI will be searching for ROMPaks (or the system DLLs).
Hmmm looking even further, they all return to the same folder as the last access, no matter which module EXCEPT the harddisk.dll which seems to retain it's filepath.

 Wasn't this addressed in the last merge?

 


Bill Pierce

**Comment by BGPierce** [comment]
All dialogs now retain their own "last path", so I am closing the issue.
Thanks :-)
