### ISSUE TITLE
Could you move the config file(s) to a user location and not in program files, please?

### ISSUE THREAD

**Issue by Alpengreis** [VCCE/VCC#3]
As the title says, would this be possible to avoid problems with user accounts (non-admin accounts), which have no write access for the config file(s)?

**Comment by BGPierce** [comment]
This is in the plan for future enhancements/updates, but honestly, I've yet to find the proper way to do this in C++. A proper C++ programmer would know exactly how to do this, but currently, there are none actively working on this project. I do the best I can with what little knowledge I have. I hope to be delving into C++ more this summer.
In the mean time, you can set the VCC.exe to "Run as Administrator" and it solves the problem in Windows 7-10.


-----Original Message-----

**Comment by Alpengreis** [comment]
Ok, thank you very much for your answer! And thanks for this program of course!

PS: I don't like to run programs as administrator (for security reasons), if they can technically run without those privilegues ... so I gave - as workaround - the related rights (change right) for the related user for the config file Vcc.ini to solve that problem.

**Comment by ejaquay** [comment]
There is a perhaps better work around to avoid running as admin.  Vcc expects vcc.ini files, dll files, and rom files to be in the same directory as vcc.exe.  Simply copy all these from program files to a user directory and run vcc from there.

**Comment by BGPierce** [comment]
The latest release has already resolved this issue.


-----Original Message-----

**Comment by ejaquay** [comment]
I see the inifile is now hardcoded in
C:\users\[user]\AppData\Roaming\Vcc\Vcc.ini   This works okay but changes
the way I was doing things.  I can deal easily enough by moving the
specific vcc.ini I want in/out of the appdata directory before/after
running vcc.   There are greyed out menu items (load/save config) I think
were intended for loading a specific ini file.  Any thoughts about enabling
these?

**Comment by BGPierce** [comment]
We are actually working on custom ini files. There's only one programmer at the moment so it takes time to get things done. everybody wants something but nobody wants to help :-)


-----Original Message-----
