### ISSUE TITLE
Emulator should "pause" while any external menu is open

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#32]
(from the old issues page)
BGPierce commented on Dec 29, 2015
Something that was brought to my attention was the way VCC's menu system works.
In Mess (and other emulators including XRoar), when a system menu is open, the emulation "pauses" and waits for you to exit the menu.
In VCC, the emulation continues to run while any menu is open. I have found this to be both an advantage as well as a hinderance.
Any thoughts on this?
B.P.

**Comment by BGPierce** [comment]
Wersley commented on Jan 6, 2016
Related to this is you can change focus from most/all open dialog boxes back to the main window.

**Comment by BGPierce** [comment]
vcc6809 commented on Jan 18, 2016
My thought, It took me weeks to figure out how to run the emulation thread asynchronous from the user interface. This is by design and should not be changed.

**Comment by ejaquay** [comment]
I think most users are happy with the way the menu system works which allows the use of settings dialogs while the emulation continues to run.  Users can always pause the emulation when they want by pressing "F7" (VCC 2.1.9.0 and up)
