### ISSUE TITLE
Using "F4" as a CPU speedup

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#33]
BGPierce commented on Dec 29, 2015
Since I run VCC quite often (read A LOT!), I find I use the increased CPU speed ("Configuration/CPU") set to the max most of the time. This setting not only speeds the CPU, but also increases screen refreshes and graphics speed. To change this setting, you open the conifg menu.
It would be nice to use F4 (unused) to set "max speed" on first press, then "minimum speed" on 2nd press.
OR.. use F3 (also unused) to slow down the CPU by 10% on each press until bottomed out, and F4 to increase the CPU by 10% on each press until maxed out. This would allow people with slower computers that cannot handle "max speed" to at least take advantage of increased speed without opening the config menu.
Any thoughts on this one?
B.P.

**Comment by BGPierce** [comment]
Luis46coco commented on Apr 13, 2017
Very easy update

**Comment by BGPierce** [comment]
BGPierce commented on Apr 14, 2017
This should activate "overclocking" the CPU, NOT "throttle" (F8 & in the display menu) as that affects the keyboard response and is almost useless. I think it was for older slow computers, but now speeds up keyboard debounce which causes one keypress to repeat many times.
"Overclocking" would be the "slider" in the CPU speed menu. If there are 2 keys available, then the best would be one key speeds up by xx steps on each press while the other slows down by xx steps on each press. Or maybe one key shifted & unshifted.

**Comment by treytomes** [comment]
I'll take the F3/F4 overclocking feature.  Sounds like a good intro feature to work on.
