### ISSUE TITLE
VCCX 4.3.0 Wish List

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#35]
(from old issues page)
BGPierce commented on Dec 29, 2015
This will be where we can start listing the things we would like to see in upcoming revisions of VCC.
Not to say it's the "Coco 4" wish list where everyone wants 1024x728 display or 2 million colors, but instead listing simple things.... things more involved with the emulator's appearence and menus and not the Coco's enhancements.
I will start a list, then everyone can chime in with things they would like to see as well. You never know, some of it may come about and be part of the new VCCX !
B.P.

**Comment by BGPierce** [comment]
BGPierce commented on Dec 29, 2015
Here is my first installment of the Wish List:

F3 & F4 keys for CPU speed in which F3 will decrease CPU speed by 10% until bottomed out and F4 will increase CPU speed until maxed out.
Force Screen Aspect Ratio - This function was started but never completed. This would keep the Coco screen the proper proportions (square) when in full screen mode (F11).
Glenside MIDI Pak emulation - This would be a cart "DLL" module that would emulate the Glenside MIDI pak. The MIDI signal could be sent to the host's MIDI input (only if available). Most OS's have a methode of selecting MIDI devices as well as software sythesizers (players). Windows uses "Microsoft GS Wavetable Synth" as a general MIDI output to the sound card.
RS-232 pak Emulation (DLL module) - This would emulate an RS-232 pak and connect to the host's serial port or TCP/IP port for communication to the outside world (and possibly better speeds to DriveWire4)
Tandy Speech & Sound Pak (DLL module) - Emulating the Tandy SSPak with the speech and sound capabilities through the host's sound card. The Orchestra90 cart (DLL) already does stereo 8 bit DAC output to the sound card and would be a good starting point.
Tandy Hires Interface & CocoMax3 Hires Interface - these would allow the use of several programs that currently will not run on VCC... CocoMax3 and ColorMax3, both of which use the interfaces. The CocoMax3 interface would also have to incorporate the "dongle" circuit for CocMax3 to run.
Direct PC harddrive file access - It would be nice to be able to load files directly from the PC host without using a dsk or vhd image. I'm not sure how this would work in RSDOS, but in OS9, the PC's HD would be treated as a normal HD... The Vcc software would have to do the conversion of file formats.
More Function Key shortcuts - When in full screen mode, VCC's menus are not available and a few more "function keys" are needed to alter several things without exiting full screen mode to access the menus (see 1 above).
These are just a few I've thought off of the top of my head... more coming.
B.P.

**Comment by BGPierce** [comment]
BGPierce commented on Jul 8, 2016
It would be nice if the "harddrive.dll" would create a VHD image if the name doesn't exist (just like the floppies). Of course, there would have to be pop-up dialog for number of sectors and such.
It shouldn't be a tough task, using the floppy image creation as a model.
B.P.

**Comment by BGPierce** [comment]
BGPierce commented on Jul 8, 2016
Another addition while in the create disk file dialog, make "JVC" disk format the default selection as that's what's used the most and is (for the most part) the standard for Coco emulators (except XRoar which uses VDK).

**Comment by ejaquay** [comment]
Several of these items have been addressed: F3 & F4 CPU speed control, forced aspect ratio, RS-232 emulation, Hires Interface, Harddive auto create vhd, and default selection of JVC disk formats.  The remaining items have each been moved to their own issue as feature requests so progress on each can be reported independantly.
