### ISSUE TITLE
Cassette interface does not remember the loaded file from each run.

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#36]
In the cassette inerface tab, when you have a cas or wav file loaded and exit VCC, the emulator will not reload this file when run again. This is not consistant with the disk and hard drive interfaces which remember the file if it was loaded on exit.

**Comment by ursine** [comment]
Pull Request #50 should have resolved this.

**Comment by BGPierce** [comment]
I'm pretty sure this HAS been resolved. We just haven't had a 'complete' working emulator (minus Becker and a few bugs), since #35  (last release), so I haven't revisted closing anything lately. I'll close it out.
