### ISSUE TITLE
VCC crashes when programs access

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#37]
Occassionally, when working on a program, a syntax error, especially involving loading data arrays or storing values to memory locations, when run, data seems to overwrite something and crash VCC. In reality, a real Coco would just "run wild" displaying a static graphics or text screen and a reset resolves the issue.
In VCC, this sometimes crashes the emulator and requiring a restart. VCC should not be doing this. It should emulate the Coco crashing just as a real Coco would.
Something is overwriting something... I have no clue as to what. This has been a problem in VCC since the beginning as far as I know.

**Comment by Wersley** [comment]
From our discussions I am convinced this the crash is caused by the unimplemented instructions in the HD6309 implementation.

**Comment by BGPierce** [comment]
I just made sure it was noted here so we wouldn't forget it.
