### ISSUE TITLE
Ramdisk cartridge

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#38]
(from old issues page)
BGPierce commented on Jan 7, 2016
Does anyone know if the "ramdisk.dll" actually works? I have never tried this module. I think it is supposed to be an emulation of Disto's Ram cart. If it actually works, I would like to document it's use and include it in the release.
I will look into this a little more.

**Comment by BGPierce** [comment]
Wersley commented on Jan 7, 2016
I have tried it and had to make changes to the DLL to get it to function properly. I will incorporate those changes soon. When I was testing it I was using the Disto drivers from NitrOS9 v3.3.0 I believe.

**Comment by BGPierce** [comment]
Wersley commented on Jan 12, 2016
Should be working with recent merge.

**Comment by ejaquay** [comment]
Works fine with the cauveat that it conflicts with FD502.dll because the both use the same IO ports.
