### ISSUE TITLE
Full Screen "flicker" and line at the bottom of the screen

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#38]
VCC displays a "line" at the bottom of the emulator "screen" (above the statusbar). When in Full Scrren mode, this line sometimes "flickers" very brightly and on a dark color screen (black background: can be very distracting. Also, somtimes, and it seems to be when full screen is entered during certain elulation "cycles" the top and bottom borders of the screen will flicker and sometimes even display (during the flicker) the actual Windows desktop in the background.
I remember Joe stating on one of the forums back when he was working on either 1.42 or 1.41, that the line below the screen was a solution to a graphics problem he was having. I think the two issues are related and that if the line is eliminated, the flicker problem will go away. I think Joes comment on the line was on coco3.com, but it could have been on the bitlist server as he posted quite a bit there as well.

**Comment by Wersley** [comment]
I have fixed this and will incorporate it soon.

**Comment by BGPierce** [comment]
I will be looking forward to this fix. This has bothered me ever since I started using VCC :-)

**Comment by BGPierce** [comment]
fixed

<closed>
