### ISSUE TITLE
F10 not working in full screen mode

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#4]
In running Vcc in full screen mode, F10 is supposed to toggle the status bar. I have notice that while in full screen mode in Vcc v2.01, this does not happen. F10 seems to do nothing.

**Comment by vcc6809** [comment]
Ill look at it, also what software uses the hi-res pack? Im trying to test the emulation but i cant find anything that uses it.

On Sep 1, 2015, at 1:48 AM, Bill Pierce <notifications@github.com> wrote:

In running Vcc in full screen mode, F10 is supposed to toggle the status bar. I have notice that while in full screen mode in Vcc v2.01, this does not happen. F10 seems to do nothing.

**Comment by BGPierce** [comment]
Joe, programs that use the HIRes pak...
Under RSDOS:
ColorMax3
ColorMax3 Deluxe
CocoMax3 (uses the CocoMax version, but may need something added for the "dongle detection", not sure)
Under OS9 L2:
MV Canvas
Ultimuse3 (switchable from normal to hires)

Also, I could write a fairly quick program to use for testing in both RSDOS and OS9 if needed.
If I think of any more, I'll let you know.

**Comment by vcc6809** [comment]
I cant reproduce this, i did find that window7 hates being forced into 8 bit color. I need to redo the direct x stuff anyway.

On Sep 1, 2015, at 1:48 AM, Bill Pierce <notifications@github.com> wrote:

In running Vcc in full screen mode, F10 is supposed to toggle the status bar. I have notice that while in full screen mode in Vcc v2.01, this does not happen. F10 seems to do nothing.

**Comment by BGPierce** [comment]
I'm running win vista (soon to upgrade) so that may make a difference. It worked for me in 1.42 & 1.43b
 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by vcc6809** [comment]
I'll try it with vista. 

On Sep 2, 2015, at 10:43 PM, Bill Pierce <notifications@github.com> wrote:

I'm running win vista (soon to upgrade) so that may make a difference. It worked for me in 1.42 & 1.43b





Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull



My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com






-----Original Message-----

**Comment by BGPierce** [comment]
I've now run the latest build of Vcc under Vista, WinXP, and Win 8. (btw, we really need to start adding incremental update version numbers.)
My Vista installation seems to be the only OS with this problem. The weird thing is that I've discovered that in Vista, I can use SHIFT-F10 and it removes the status bar. All other function keys work without the SHIFT (?)
So I guess I'll close this issue as it was probably never an issue to start with and is some weird property of my OS
BTW, Full Screen mode is pretty awsome!
I use a 19" square LCD monitor, so it actually looks like a Coco screen when in full screen, just bigger. On WinXP, I use a 13" square monitor, nice as well :-)
This is a screenshot of Vcc running my MShell project under NitrOS9 3.3.0 on my 19" square monitor in full screen mode:

![mshell fullscreen 1](https://cloud.githubusercontent.com/assets/10055926/10496761/3c66c602-7290-11e5-80bd-b7d449a5d123.jpg)

Bill
