### ISSUE TITLE
Missing 6309 instructions

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#40]
It has come to my attention that there are some 6309 instructions missing from the 6309 emulation in VCC. It would be nice to have the full 6309 implementation in VCC.
I haven't actually seen problems with this that I know of, but I know some adventurous programmer will catch it.

**Comment by Wersley** [comment]
I believe this to be a duplicate of #37 .

**Comment by BGPierce** [comment]
Actually no... at least as for the nature of the bug itself. #37 "may" be caused by the missing 6309 instructions, but ultimately, VCC should not crash on ANY bad instruction or memory read/write. The example of the crash you saw was just one example... I've crashed it may ways other than that one.

 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by ursine** [comment]
What instructions are actually missing?

**Comment by BGPierce** [comment]
Gary, I'm not sure which instructions are missing, but I do remember there being discussion on it one time, long ago on the coco3.com forum. Wes may know more about this than I do, but he seems to have disappeared for a bit.
 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com

**Comment by abathur8bit** [comment]
Full list is now located in the new file in Docs/VCC-Notes.md. Also note there is a huge bunch that are listed as untested. Listing unimplemented instuctions here for reference:

- ADCD_D UNEMULATED
- ADCD_E UNEMULATED
- ADCR   UNEMULATED
- BAND   UNEMULATED
- BEOR   UNEMULATED
- BIAND  UNEMULATED
- BIEOR  UNEMULATED
- BIOR   UNEMULATED
- BOR    UNEMULATED
- DIVQ_D DONE
- DIVQ_M DONE
- DIVQ_X DONE
- DIVQ_E DONE
- LDBT   UNEMULATED
- SBCD_D UNEMULATED
- SBCD_E UNEMULATED
- SBCR   UNEMULATED
- STBT   UNEMULATED

**Comment by BGPierce** [comment]
Fixed.

<closed>
