### ISSUE TITLE
RS232 pak dll feature

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#45]
(from the old issues page)
abcbarryn commented on Feb 3, 2016
It would be really nice to have an RS232 pak emulation that would connect to an IP and port address. That way I could use VCC to run terminal software or accept incoming connections without using a DriveWire server. DriveWire becker port support is nice, but having to run a server process just to get this ability is a pain.

**Comment by BGPierce** [comment]
ursine commented on Dec 16, 2016
I wonder if the two could be merged? The Becker port seems really like a specialization of the ability to connect to an arbitrary port for RS232 running a particular protocol.

**Comment by BGPierce** [comment]
abcbarryn commented on Dec 16, 2016 • 
The Becker port/Drivewire protocol also allows you to access files and storage over the network and requires a separate server. The idea I had here is:

To not require a separate server.
To emulate an RS232 pak and a modem using the network and TCP/IP instead of disk storage.
To be compatible with existing RSDOS terminal software.

**Comment by ejaquay** [comment]
New acia.dll addresses this.   Will close after some bugs worked out.
