### ISSUE TITLE
The "SuperIDE.dll" does not work

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#47]
(from the old issues page)
BGPierce commented on Sep 2, 2016
In the current release (from vcc-1.200b, not the master), I've found that the "SuperIDE.dll" does not function. Everything seems to work up until it goes to read the drive on restart after making the proper setting in all the configs. I get the hdblba error "LBA Hard Drive Not Found", when there is a CF card image mounted.
I have tested these settings on both VCC 1.42 and VCC 1.43beta and the SuperIDE.dll works properly.
This may not be an issue once the latest commint is finally made as I know quite a few things are being rerranged.

**Comment by BGPierce** [comment]
ursine commented on Sep 2, 2016
@Wersley Is the current master branch up to date with where you are, or are you still rearranging?

**Comment by BGPierce** [comment]
BGPierce commented on Sep 2, 2016
I'm pretty sure he hasn't commited those last changes. I think he ws still working on a couple of things when overtime hit him.

**Comment by ejaquay** [comment]
Issue was related to use of buggy rom and conflict with FD502 clock.   Clock resolved by unclicking clock at 0xFF50 in FD-502 config.  Corrected rom will be distrubuted with next VCC release
