### ISSUE TITLE
Code is split between C and C++

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#49]
(from old issues page)
ursine commented on Dec 14, 2016
The VCC code base is currently made up of a hybrid of C files and C++ files. The compiler decides which it is by checking the extension: ".c" gets compiled using the C compiler, ".cpp" gets the C++ compiler.

Currently VS 2015 does not completely support modern C and this causes some minor hand holding to be required. Changing all of the .c extensions to .cpp will cause the C++ compiler to be invoked, giving access to modern code features of C++11/14, as well as the use of the common subset of modern C.

It should be as simple as changing the extensions and submitting it, but there's always possible issues. I plan to do this shortly. (If there are any concerns please discuss soon)

**Comment by ejaquay** [comment]
C and C++ have different scoping and mangling rules.  Changing how source is compiled would require code changes.  More pain than gain in my opinion.

**Comment by ejaquay** [comment]
Vcc proper is configured to compile using c++.  New work should use .cpp extension to avoid confusion.  DLL builds will remain as they are unless re-write is required.
