### ISSUE TITLE
virus detected in zip file

### ISSUE THREAD

**Issue by ghendric** [VCCE/VCC#5]
Bitdefender detected a virus within the .ZIP file when I extracted the files. Not sure if thats a false positive but somebody should probably take a look at it.

The file wimgtool-os9.exe is infected with Gen:Trojan.Heur.GC.O9Z@q9iuvriib and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by BGPierce** [comment]
False positive.
Virus software flags any program that modifies it's own program space, which the installer does.

**Comment by ghendric** [comment]
Bitdefender keeps disinfecting it just from extracting it or copying it to another folder..

**Comment by Alpengreis** [comment]
@ghendric

Then report it to Bitdefender as false positive. As a workaround you should be able to exclude it for scanning in Bitdefender ...
