### ISSUE TITLE
Condense Plugins into main code base

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#50]
(from old issues page)
ursine commented on Dec 16, 2016
Currently, the code is split into many plugins. Given that the system is now open source, having an external API is likely unnecessary. I would like to propose condensing the plugins into the main codebase. This would allow the compiler/linker greater insight into the code for optimization purposes, as well as reducing the system to a single exe rather than a bunch of dlls and an exe.
Thoughts/Ideas/Objections?

**Comment by BGPierce** [comment]
Luis46coco commented on Apr 12, 2017
Interesting, but the main idea for this (I think) was to be able to update a *.dll cartridge without affecting the others, so there may be versions 1,2,3, orchestra-90 and the floppys controller is still in the version 1 (for example)

**Comment by ejaquay** [comment]
Use of DLL's for peripherals is an important feature of Vcc.
