### ISSUE TITLE
Need the Rs232 Pack in order to bring back Ribbs

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#53]
ptaylor1984 commented on Feb 6, 2018
I would like to see the old Rs232 pack and some folks are showing more interested with running a bbs system. Using the same functions and features of the old Rs232 Pack would save from having to write several hundred lines of codes if it support the same memory address to receive, send and carrier detect. The incoming data control can be controlled using timer evens which most programing languages support to slow down the data to 9600 baud. So lets bring back the old bbs system because calling a bbs is not a real coco bbs unless its running on the Trs-80.

**Comment by ejaquay** [comment]
Does anybody have a copy of the pak rom?

**Comment by MidnightThunder** [comment]
Would really love to see the RS-232 pack implemented, I'm sure it could be done.
