### ISSUE TITLE
Open Cartridge Program pack

### ISSUE THREAD

**Issue by Luis46coco** [VCCE/VCC#67]
I have seen that it is difficult to load cartridges because it does not contemplate the extension * .ccc nor * .pak

I think and if you agree to put this in the window filter on pakinterface.c (int LoadCart(void))

Ofn.lpstrFilter = "Program Packs (*.rom; *. dll)\0*.ROM;*.DLL\0Cartridges (*.ccc; *.pak)\0*.ccc;*.pak\0All Files (*.*)\0*.*\0"; // filter string

instead of this
Ofn.lpstrFilter = "Program Packs \ 0 * .ROM; *. DLL \ 0 \ 0"; // filter string

So we can choose 3 options and also see the extensions you are currently looking for

(How do I put labels here?)

**Comment by BGPierce** [comment]
The "*.ccc" format will most likely be in the next revision of VCC. The "*.pak" format however may take longer as code would need to be written to handle the header and footer in this format.

<closed>
