### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by Luis46coco** [VCCE/VCC#69]
I do not know if it is a good idea to have inside the code the distribution tables of the keyboard, I know that for convenience there are no external files, but that makes many things impossible.

The added languages are not a problem since there are helpers in VS2015 that allow in addition to translate, use even different sizes for fields in the dialogs and buttons, being able to change its size to adapt it to other languages.

But in PC,MAC or ... keyboard layout, no

I propose to change this to a file that can be modified even by the user, thinking about how difficult it is for German users with double accents, this way we can go out versions of keyboard designs or each one sends us one and we go Collecting

For this you need an external file, if it's okay with you, I get to work on that

**Comment by Luis46coco** [comment]
I have seen that in the original Welcome to VCC manual there is a screen in keyboard configuration that is key by key

I would like to repornan to that idea, of course having the automatic coconut keyboard combobox and adding a PC keyboard with several settings for each country, but some subtle personal changes are always necessary

Does anyone have those old source codes?

**Comment by BGPierce** [comment]
Luis, the inclusion of a "custom keyboard editor" is actually on the wish list. How and when it will be implemented is another story :-)

<closed>
