### ISSUE TITLE
"Overclock Disk Drive" not persistant

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#7]
In Vcc v2.01, I have noticed that the "Overclock Disk Drive" checkbox under the "FD-502 Config" is not persisting from one run to the next. I find I have to check this box each time I run Vcc.
I've checked the "vcc.ini" file and the value for this feature is being written to the vcc.ini properly. All other featurs under this menu persist to the next run. This feature did in older versions.
This isn't anything major... just annoying if you use this feature as regularly as I do :-)

**Comment by ursine** [comment]
Closed it, but then realized I should probably wait until the fix is merged -- just in case.
