### ISSUE TITLE
I suggest that you use a PC dir as a hard disk or as a floppy disk

### ISSUE THREAD

**Issue by Luis46coco** [VCCE/VCC#72]
I suggest that you use a PC dir as a hard disk or as a floppy disk
As floppy disk would not have limitations, I do not know if it would work well but you can study

As HD would be better, there would be no need to create an HD file and we could also pass directly without conversions .bas or .bin files as is done in other emulators like winUae for friend

**Comment by BGPierce** [comment]
Luis, one of the many problems with "direct disk access" is that when you are writing using your own file system on a PC system drive, you stand the chance of one errored write trashing your entire PC HD. This is the very reason almost all emulators use the 'virtual disk' format for drives (even VMs do this). Then the only thing you trash is the virtual disk itself.
