### ISSUE TITLE
The wiki link seems to be broken

### ISSUE THREAD

**Issue by johng42** [VCCE/VCC#74]
I tried clicking the wiki link (to get to the documentation referenced in the readme) but the link just redirects me to the current page:

Go to
https://github.com/VCCE/VCC
click the Wiki link (https://github.com/VCCE/VCC/wiki)

result:
I get directed back to https://github.com/VCCE/VCC

**Comment by BGPierce** [comment]
The wiki is down for the moment, but will be back soon.
The documentation is included in the download. If you use the installer, the manual will be installed to "Documents/Coco Manuals". There should also be a link to the manual in your Start Menu.
If you used the zip instead, the manual will be in the VCC installation folder.


-----Original Message-----
