### ISSUE TITLE
Inno Installer script and support file

### ISSUE THREAD

**Issue by mevenson** [VCCE/VCC#75]
Is there any chance the files required for the Inno Script and the script itself can be added to the solution?

**Comment by BGPierce** [comment]
The Inno Installer is a copywritten program, though it IS opensource (sort of) and available here on GitHub.
The actual script file is mostly directory locations which would be of no use as they point to my personal hard drive directories.
I used one of Inno's templets to create my script and then modified it to fit my needs.
If you need some help with Inno, email me personally and I may be able to help.
Bill P.


-----Original Message-----
From: Michael Evenson ***@***.***>
To: VCCE/VCC ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Tue, Mar 16, 2021 7:44 am
Subject: [VCCE/VCC] Inno Installer script and support file (#75)

Is there any chance the files required for the Inno Script and the script itself can be added to the solution?—

**Comment by mevenson** [comment]
Bill,

 

              Actually, I do have Inno installed. What you described is exactly what I was looking for. The .iss file would be great. I could modify it to point to my directories. It would let me know what to include in the installer. Any bits and bobs that are not actually in the solution or generated by it would also be nice. Perhaps I could genericize it so that it would require minimal changes on another persons system.

 

BTW: - What a great job you did in putting this whole thing together. 

 

Mike

**Comment by BGPierce** [comment]
Michael, I could send you a copy privately. I am also happy to answer any questions you may have. I just don't really see the need to post it to the repo.
Just get up with me on the Coco mail list or the Coco FB groups.


-----Original Message-----

**Comment by mevenson** [comment]
‘Just get up with me on the Coco mail list or the Coco FB groups.’ <- I do not know what this means.

**Comment by BGPierce** [comment]
Just email me at ***@***.***


-----Original Message-----

**Comment by mevenson** [comment]
Unfortunately github obfuscates email addresses in it’s emails. Mine is Michael.evenson at flexusergroup dot com
