### ISSUE TITLE
Socmaster's Matrix does not work in VCC (latest)

### ISSUE THREAD

**Issue by Rondelvo** [VCCE/VCC#78]
Try it...blank screen...if you keep hitting your mouse it slowly shows the characters ...but does not run.

**Comment by BGPierce** [comment]
This is actually a known issue. The video timing in VCC is slightly off and Sock's demos require precise timing. There are several other similar things that won't work as well.
We've worked on it but still haven't found exactly what's going on yet.


-----Original Message-----
From: Rondelvo ***@***.***>
To: VCCE/VCC ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Thu, May 13, 2021 6:08 pm
Subject: [VCCE/VCC] Socmaster's Matrix does not work in VCC (latest) (#78)

Try it...blank screen...if you keep hitting your mouse it slowly shows the characters ...but does not run.—

**Comment by ejaquay** [comment]
Tested Jan 21, 2024. VCC 2.1.8.2  Seems to work now. Glyphs with RGB are somewhat brighter than with Composite
