### ISSUE TITLE
Still not fixed....the palettes in Hicolor2 are off  

### ISSUE THREAD

**Issue by Rondelvo** [VCCE/VCC#79]
If you try Hicolor2 and once its up...you press d and l and load a bmp thats 320x200x256  it looks bad....but
if you press a, b, c, then d then l and load the bmp  the color is correct.
![Image3](https://user-images.githubusercontent.com/84157404/118194882-fba6a680-b3fe-11eb-99d1-79852968e42c.jpg)
![Image5](https://user-images.githubusercontent.com/84157404/118194887-fe090080-b3fe-11eb-96a9-5ac314adcaed.jpg)

**Comment by Rondelvo** [comment]
I hope this helps!

**Comment by BGPierce** [comment]
This maybe related to the video timing issue in "Issue #78".


-----Original Message-----
From: Rondelvo ***@***.***>
To: VCCE/VCC ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Thu, May 13, 2021 6:22 pm
Subject: [VCCE/VCC] Still not fixed....the palettes in Hicolor2 are off (#79)

If you try Hicolor2 and once its up...you press d and l and load a bmp thats 320x200x256 it looks bad....but
if you press a, b, c, then d then l and load the bmp the color is correct.

**Comment by ejaquay** [comment]
This should be fixed as of VCC v2.1.0.8
