### ISSUE TITLE
VCC 2.0.1 binary released & VCC 2.0.1 Wiki started

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#8]
I have taken the liberty of releasing the compiled version of "VCC 2.0.1". I have been running it for a little over a month now and only a couple of things have cropped up which are all (so far) listed in the "Issues" as "bugs". The release is packeged in an "Inno" installer package along with a newly revised manual. I also included all needed roms. The "Tandy" roms were compiled from the "ToolShed" repository and therefore are NOT copies of the Tandy roms.
The HDBDOS and RGBDOS roms were released into Open source, so they are legit.
I have aquired permission from Jon Bokelman & Brian Eggars to use the Orchestra-90 rom

I also have started a "Documentation" wiki which basically reflects the new manual. If you have any changes or suggestions, let me know and we'll get them in there and in the new manual as well.

**Comment by RobertGault** [comment]
I cannot get VCC 2.0.1 to run on a WinXP SP3 32-bit system. Windows throws an error and says that Vcc.exe is not a Win32 application.

**Comment by BGPierce** [comment]
Robert, I'm not sure, but I have a feeling it's been unknowingly compiled for a 64 bit system. I can run it on my Vista HP 64 bit. I have a "Win Server 2005" install that's 32 bit, so I'll check it on that and see what happens. We're probably going to have to recompile it anyway.

**Comment by ursine** [comment]
I checked the configuration manager to see what platform the solution is targeted for, and it is x86, not x64.  So, that is likely fine.  My hypothesis would be that the runtime library is missing.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

It could be built into the package and run via the installer.  

@RobertGault could you try installing that and then running the binary?

**Comment by BGPierce** [comment]
Gary, I hadn't thought of that. It could very well be the runtime packge. I could include it in the installation if this is the problem.

I'm so used to my system having multiple runtime packages from hundreds of installations of my pro audio software, I forget others may not have it.

 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by BGPierce** [comment]
When you guys get a chance, look over the Documentation Wiki page and see if anything is missing or if there are any errors. The wiki is basically straight from Joe's old PDF manual for 1.42, with a few expanded instructions as well as the addition of a Becker Port page.
Let me know if I need to change anything. This is basically what the PDF manual looks like which I include with the binary release packages.
Bill

**Comment by ursine** [comment]
Since this has been released in a final version, can we close this issue?

**Comment by writeson** [comment]
Hi,
Hope someone is still checking this. :) I'm trying to run the VCC 2.0.1b version on Windows 10, which is a guest OS running in VirtualBox on my Mac Sierra OS. The emulator opens up and as far as I can tell is running, but the screen is completely black. No setting I can change in the configs seems to affect this. I've tried going back to the 1.42 version (which I had running on a Windows guest running in Parallels on a different Mac), but it fails as well. 

Any hints how to get it running with screen display in my rather wacky configuration?

Thanks,
Doug

**Comment by BGPierce** [comment]
Doug, I've run this release on XP, Vista, 7, 8, & 10 (32 & 64 bit) and had no problems. I've heard no reports on this happening on Win 10, so I assume something is missing in your VM. VCC currently requires Directx, so you may want to check, but I'm pretty sure 10 does an auto-install of DX. Could be a graphics driver issue.. make sure they're the latest as win 10 gets picky about such things and VMs are finicky as well.

 

 

Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page

E-Mail: ooogalapasooo@aol.com

 

 

-----Original Message-----

**Comment by drencorxeen** [comment]
Doug,

You may wish to try installing the web setup utility for directx that is from Microsoft's website.
https://www.microsoft.com/en-us/download/details.aspx?id=35

I know Windows 10 itself does not install all DirectX components by default.  So some of the older games or applications that need components from older versions of DirectX you will need to use a installer from that time frame.  I hope this helps you out.
