### ISSUE TITLE
No sound using Wine

### ISSUE THREAD

**Issue by hpmachining** [VCCE/VCC#81]
When I run the emulator in Linux using wine, I can't get the sound to work. There are no options in the "Output Device"  drop down in Configuration->Config->Audio. This may very well be an issue with wine and not vcc but I thought someone here may know how to get it to work. I am running Debian 9.4, Wine 1.8.7, and VCC 2.01b w/Becker Port.

**Comment by abathur8bit** [comment]
I haven't tried using wine. VCC does use the API call DirectSoundEnumerateA() to find all sound cards that are attached. Sounds like it isn't finding anything under wine. I'd try posting to the Facebook group. If you find anything further I'd like to document it.

**Comment by hpmachining** [comment]
I did manage to get the sound working in Arch Linux (64 bit) by installing `lib32-alsa-plugins lib32-libpulse lib32-openal` as per this link [wine sound not working](https://bbs.archlinux.org/viewtopic.php?pid=1054339#p1054339). Debian doesn't have those packages in their repositories, so I am still researching to find a solution for Debian 64 bit. If I find a solution I will post here. Thanks!
