### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by mdavidjohnson** [VCCE/VCC#82]
I'm running VCC 2.01 under Windows 7 Pro (64-bit) SP1 on an HP p6774y AMD Phenom II X4 840T 2.90 GHz with 16.0 GB RAM.

Whenever I minimize VCC 2.01, it doesn't seem possible to re-open the window. 

Clicking on the minimized icon results in a brief flash on the screen, but then nothing.

[Right Click|CoCo VCC Emulator] opens a new instance of the emulator, not the original which was minimized.

**Comment by BGPierce** [comment]
I run Win7 pro as well on an AMD quadcore. I have no problems minimizing and maximizing VCC as well as running full screen. I also run VCC on a Win8 laptop and an WinXP setup. Non of these show any of the symptoms you describe.
I would suspect the problem being with either your graphics card driver, or your Win7 system settings or missing DirectX runtime (VCC needs the DX9 runtime)

 

 

Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull
