### ISSUE TITLE
VCC 2.01 can't unload fd502 external rom 

### ISSUE THREAD

**Issue by MacFadzen** [VCCE/VCC#83]
under debian/stretch/wine 
It could be me but in the fd502 config after loading an external rom could not find a way to unload it, unclicked  persistent images .  Reinstalled VCC and kept a copy of VCC.ini , recreated the problem, replaced the following VCC.ini with the copy from the reinstall and the rom was clear  

from vcc.ini after the rom load.
           [FD-502]
           DiskRom=2
           RomPath=disk11.rom
           Persist=0

reinstalled VCC to clear

an option in config misc to restore VCC to original install values would be good, at least for me 

thank you

**Comment by BGPierce** [comment]
I've never had a reason to unload the rom, so I never noticed the behavior.
The rom is easily replace by using the "External ROM" or "RGBDOS ROM" options, therefore negating any reason to unload the ROM.
I'm pretty sure, the disk11.rom is loaded automatically when the FD502 is loaded, so once a path is known, it will always load on startup. This is possibly a leftover from 1.42 when the original Tandy/Microsoft ROMs were built into the sources.
If you want to use something like ADOS-3, just use the "External ROM" option in "FD502 Config".

 

 

Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page

E-Mail: ooogalapasooo@aol.com

 

 

-----Original Message-----
