### ISSUE TITLE
DOUBLE SIDED VIRTUAL DISK

### ISSUE THREAD

**Issue by dpMerchant** [VCCE/VCC#85]

**Comment by dpMerchant** [comment]
How can I use both sides of a double sided virtual disk in VCC? Why can it make them If I can't use both sides?

**Comment by BGPierce** [comment]
If you are referring to RSDOS, it has nothing to do with the disks as RSDOS is written to only access one side of a drive at 35 tracks regardless of the drives capability. Blame Tandy. This is true on ANY emulator or even the real machine. There are many "alternate" DOSes written that will access both sides such as "ADOS", which will access side 2 as another drive.
On the other hand, OS9/NitrOS9 will access both sides of a drive as a single, large drive. In fact, OS9/NitrOS9 will access many kinds/sizes of drives just by changing the driver/descriptor.


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull
