### ISSUE TITLE
I am a noob

### ISSUE THREAD

**Issue by Chaython** [VCCE/VCC#88]
Hello, my grandpa has distant memories of a game called Erland 
http://www.colorcomputerarchive.com/search?q=erland&ww=0&cat=&cs=0
He hardly remembered the name, let alone the platform. A year or two ago I spent several hours searching for it, and found it on some archived forum[now there's the great resource linked above], and found out it was for the TRS80 COCO? I then tried to find an emulator to run this .dsk ; in VCC if I select to open a cartridge , the DSK doesn't even appear. I've tried a few other emulators to no avail. If I drag Erland into the VCC it just says ex in the top corner... Please help me, recommend an emulator / set one up for me.... Hardware is not a choice my grandparents live in a mobile home, and I don't think that my grandpa will play it much[if at all], he just has his distant memories and I want to feed his nostalgia....
My grandpa probably will hardly play it, but he remember spending so much time on it and has no interest in any other games... This search probably wasn't worth my time, but my grandpa said he tried to find it years ago as well [XP era]... So I'm trying for him.
Thanks.

**Comment by BGPierce** [comment]
First I suggest reading the manual that comes with the installation package with VCC. Once installed, it can usually be found under "(My)Documents/Coco Manuals".
As the manual states, to use a virtual disk image ("*.dsk"), you must first attach a virtual disk drive. To do this, Go to the "Insert Cartridge" menu, navigate to your VCC installation folder, select "fd502.dll" and click OK. Now you will notice that the cartridge menu has changed and will allow you to insert a disk into drive 0.
Also found in the manuals is a Disk basic manual which gives you the instructions on using a disk drive. But basically, after inserting the disk type:

DIR<ENTER> - views the files on the disk

If the desired filename ends in "BAS", you type:
LOAD"FILENAME/EXT"<ENTER> - Loads the desired file into memory
RUN<ENTER> - run the loaded file

If the desired filename ends in "BIN", you type
LOADM"FILENAME/BIN"<ENTER> - loads the desired file
EXEC<ENTER> - runs the desired file
 
 
 
-----Original Message-----

**Comment by Chaython** [comment]
I loaded the fd502.dll for the disk drive
I loaded the DSK
It returns Erland Bin 2 b 12

> If the desired filename ends in "BIN", you type
LOADM"FILENAME/BIN"<ENTER> - loads the desired file
EXEC<ENTER> - runs the desired file
I tried many times to no avail with and without caps lock quotation marks don't load in this system, but I assumed you just quoted as a separator I added spaces tried without m, tried . like a windows extension....
LOADMERLAND/BIN
LOADM ERLAND/BIN
LOAD ERLAND/BIN
LOAD ERLAND.BIN
LOADM ERLAND.BIN
LOADRLAND/BIN
ETC ETC
I just get "?/0 Error"
`%userprofile%\documents\coco manuals`

**Comment by BGPierce** [comment]
The quotes & ALLCAPS ARE required. The proper syntax is:

LOADM"ERLAND/BIN"
EXEC

If that doesn't work, then I'm not sure what the problem is. Maybe a corrupt disk image.

In fact, I just downloaded the same disk image and ran the program. It runs fine :-)
 
 
 
-----Original Message-----

**Comment by Chaython** [comment]
Sorry, the default coco keyboard didn't have quotations assigned to the same key and I didn't realize the quotations were required
Thanks!
