### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jejones3141** [VCCE/VCC#89]
Is there any documentation for VCC?

**Comment by BGPierce** [comment]
James, if you downloaded and installed VCC 2.01, the manual should be installed with the installation.
Look in "%Home%\Documents\coco Manuals". The Manual is titled "Welcome To VCC".
 
 
 
-----Original Message-----

**Comment by jejones3141** [comment]
Thanks! I installed it with WINE, so I'll look in the corresponding place.

**Comment by BGPierce** [comment]
Also, the manual is identical to the Wiki here on the site
 
 
 
-----Original Message-----

**Comment by jejones3141** [comment]
Thanks. The documentation is very helpful, and I'm up and running.
